### ISSUE TITLE
communication error with nuki bridge

### ISSUE THREAD

**Issue by Blastmun** [dauden1184/RaspiNukiBridge#10]
I followed your tutorial and thank you! I have an error when integrating the new device. What is the web API token and the bridge API token?

in nuki lock I can put http://@:p ort + Token of nuki.yaml file but it does not work

**Comment by dauden1184** [comment]
Are you integrating the device in homeassistant?

The web api token is to contorl the smartlock using the nuki servers, it has no use for this software.
The bridge token is the one generated with the `python . --generate-config > nuki.yaml`, so you can find it in your nuki.yaml (the `token` field)

**Comment by Blastmun** [comment]
Thank you for your reply.
Yes it is to integrate it with "Nuki lock" in HA
I have configured port 8085 in my config file. It is on a ft3 B and the CLI commands to open and close work perfectly
![image](https://user-images.githubusercontent.com/106776511/171989237-d27bcfaa-0eb6-4488-9509-05cdea254e40.png)

**Comment by dauden1184** [comment]
Try to run this command on the raspberry: `netstat -naep | grep 8085` to check if the port is open
