### ISSUE TITLE
Open door function

### ISSUE THREAD

**Issue by Timo1993** [dauden1184/RaspiNukiBridge#13]
Is there a way to add the open door function of the app? It works well to lock and unlock the door. But my door has a door knob so I need an open door function.

Best regards

**Comment by dauden1184** [comment]
The unlatch command is supported.
Are you using it with homeassistant?
Homeassistant doesn't have a button to call the unlatch command, but you can call the service

https://www.home-assistant.io/integrations/nuki/#service-nukilock_n_go
