### ISSUE TITLE
Error pairing: PY_SSIZE_T_CLEAN must be defined

### ISSUE THREAD

**Issue by juanrferia** [dauden1184/RaspiNukiBridge#17]
Hello. When executing the step for pairing _python . --pair MAC_ADDRESS_ I get the following error:

![image](https://user-images.githubusercontent.com/11686949/207982706-6a673664-9524-45b9-affe-581d4ed165ef.png)

I appreciate if anyone can help me to fix it. Thanks

P.S.: Apologies for updating an screenshot, the environment I'm working does not allow me to copy/paste.

**Comment by dauden1184** [comment]
Hi, what python version are you using?

**Comment by juanrferia** [comment]
python 3.10. 
I'm trying to install it through the SSH & Web Terminal addon from Home Assistant.

**Comment by dauden1184** [comment]
Is it possible that some of the library used are not updated for python 3.10, can you try with 3.9?

**Comment by juanrferia** [comment]
Hi. Maybe. I finally decided to use another library based on yours, which worked. I took that post: https://community.home-assistant.io/t/using-nuki-lock-3-0-fully-local-without-bridge/490527 
Thanks!
