### ISSUE TITLE
MAC address check is case-sensitive.

### ISSUE THREAD

**Issue by theorician** [dauden1184/RaspiNukiBridge#20]
First of all thanks for a great project.

I tend to write my MAC addresses lowercase. When writing the config yaml file, I wrote the MAC address for my Nuki (found via a BLE scanner as described in your README) lowercase as well. As a consequence, the check at https://github.com/dauden1184/RaspiNukiBridge/blob/2f450b2a02c1816a284c8dfc2e6cc7b0d84d1783/nuki.py#L180 doesn't return my device. 

A helper method which lowercases both inputs might make this a bit more robust - it took me a fair while to figure out why my device wasn't being shown.

(As an aside: the yaml file being auto-generated so that the user never has to edit it would make all this largely redundant - and be a lot easier for the end user as well.)

Thanks again!

**Comment by dauden1184** [comment]
Thanks! The MAC case sensitive issue should be fixed with the last commit.
