### ISSUE TITLE
Nuki Opener support

### ISSUE THREAD

**Issue by TondaRuzicka** [dauden1184/RaspiNukiBridge#21]
Hi,

Thanks for the time you put into this project. I'm thinking about buying Nuki Opener, but I don't want to buy the bridge as I have a Rapsberry P Zero 2 W. 

I just want to make sure your project supports the Opener, right? I saw [this thread](https://github.com/dauden1184/RaspiNukiBridge/issues/3#issuecomment-1235778822), but it's not clear to me.

Thanks,

Tony

**Comment by dauden1184** [comment]
Hi, the Opener is supported only partially.
It seems that this software is not able to get the ring notification, not having a Nuki Opener myself it quite hard to debug :(

**Comment by TondaRuzicka** [comment]
@dauden1184 thanks for the info. Would this info help you? https://developer.nuki.io/t/node-red-detect-ring-via-node-red-opener-and-bridge/18737/2.
