### ISSUE TITLE
Duplicating NukiBridge device in Home Assistant

### ISSUE THREAD

**Issue by chrispazz** [dauden1184/RaspiNukiBridge#22]
Hello,
I am successfully using this software Nuki Bridge.
The only problem is that sometimes it re-generate itself as new device in home assistant.
The bridge continues to work ok but I have a lot of "dead" bridges as picture below....(i have disabled the dead ones).

![NukiBridge](https://user-images.githubusercontent.com/982153/234648276-effff6ac-6414-498f-bec2-badfa5e204ac.jpg)

Why is happening this?

Thank you
Chris

**Comment by chrispazz** [comment]
Thank you for fast update.
Help: best and fastest way to update the software keeping my configuration? :)

**Comment by dauden1184** [comment]
If you cloned the repository with git you can just pull the last commits.
Anyway, all the settings are in the `nuki.yaml` file, so just be sure you keep this file
