### ISSUE TITLE
Add support for opener

### ISSUE THREAD

**Issue by Bladestar2105** [dauden1184/RaspiNukiBridge#3]
Hello!

Your Bridge works very well with the smartlock!
Could you please implement support for the opener?

And another question. How can I enable it so it autostarts when my Linux comes up?

**Comment by dauden1184** [comment]
Hello,

I don't have a Opener so I cannot test it, I will look into it anyway but I probably will need some help from you while debugging.

For start the software automatically you can create a systemd service, I will add a small guide to the readme in the next days

**Comment by Bladestar2105** [comment]
Tell me what you need and I can help you :-)

**Comment by dauden1184** [comment]
Were you able to pair the opener with the software? what kind of issues are you having?

**Comment by dauden1184** [comment]
> And another question. How can I enable it so it autostarts when my Linux comes up?

Added instructions for this in the README

**Comment by maddingamer** [comment]
Hi, I just found your repo and I'm getting an opener soon and want to use some kind of software bridge. I will try it out and would be happy to help adding support for the opener :)

**Comment by maddingamer** [comment]
Foud the documentation for opener: https://developer.nuki.io/page/nuki-opener-api-1/7

**Comment by dauden1184** [comment]
I see that there are not many differences from the smartlock, you should be able to pair the opener with the software.
Can you confirm this? after this I'll add the missing actions for the opener

**Comment by maddingamer** [comment]
Sounds promising, I haven't tried or even installed your software yet. I will try today evening or tomorrow morning and will give an update.

**Comment by maddingamer** [comment]
It took me a few tries, but it seems to have worked. 

Output in a pastebin as I am too stupid to properly format in here 😂 
https://pastebin.com/K8AG1fNK

**Comment by dauden1184** [comment]
So, this happens while trying to pair the opener?

**Comment by maddingamer** [comment]
> So, this happens while trying to pair the opener?

Exactly. Took me a few times to get it to kinda pair tho.

**Comment by dauden1184** [comment]
The pairing seems to not be completed, I'll look into it. Please try to run the pairing command with the --verbose flag to have more logs (remember to hide any personal information in it)

**Comment by maddingamer** [comment]
> Please try to run the pairing command with the --verbose flag to have more logs (remember to hide any personal information in it)

It seems like it doesn't make any difference using --verbose flag. Output is exactly the same.

**Comment by dauden1184** [comment]
So, it seems the software cannot find the ble characteristic used by the pairing process (but on the docs it's the same as the smartlock, so that's strange).
Anyway I just added some verbose logs so, if you can, update and try again with the verbose logs flag please

**Comment by maddingamer** [comment]
I'll try again with verbose logs once I get home!

**Comment by maddingamer** [comment]
Here you go: https://pastebin.com/Q8GUcZ0m

**Comment by dauden1184** [comment]
uhm, It seems the values of the characteristics in the official docs is wrong?
Can you please try to edit the file `nuki.py` an change these lines:

```
BLE_SERVICE_CHAR = "a92ee202-5501-11e4-916c-0800200c9a66"
BLE_PAIRING_CHAR = 'a92ee101-5501-11e4-916c-0800200c9a66'
```

with these:

```
BLE_SERVICE_CHAR = "a92ae202-5501-11e4-916c-0800200c9a66"
BLE_PAIRING_CHAR = 'a92ae101-5501-11e4-916c-0800200c9a66'
```

and run it again?

**Comment by maddingamer** [comment]
> uhm, It seems the values of the characteristics in the official docs are wrong? 
Interesting 🤔😂

Got another error now: https://pastebin.com/RuJpicRq

**Comment by dauden1184** [comment]
It seems the error is that the opener isn't in pairing mode.
You should press the button on the opener for 5 seconds in order to set it in pairing mode, did you do this?

**Comment by dauden1184** [comment]
yes, that's good! the pairing process is completed, you can copy the info in the yaml file (as explained in the readme) and start the software.

**Comment by maddingamer** [comment]
Makes sense as the opener is not supported by homekit at all. 

Thanks! Let me know when to update and try again! :)

**Comment by dauden1184** [comment]
You can update the software and try again

**Comment by maddingamer** [comment]
> You can update the software and try again

Seems like the same problem as yesterday when pairing https://pastebin.com/zTsf1gTL

**Comment by dauden1184** [comment]
It seems that there are problems with the pairing procedure but you already paired it yesterday, so It should be not necessary to do it again. can you start the software normally? (I'll fix the pairing procedure in the meantime)

**Comment by maddingamer** [comment]
I did a fresh start by downloading the repo again into a new folder, so I guess I have to pair it again first, sorry.

**Comment by dauden1184** [comment]
ok, i think i fixed it, try again please

**Comment by maddingamer** [comment]
Pairing completed.
When starting the software its saying this in a loop (added the opener as smartlock, as it seems to expect a smartlock in the yaml):

https://pastebin.com/7Y6JTcPP

**Comment by dauden1184** [comment]
Updated the code, please try again!

**Comment by maddingamer** [comment]
Done.
It's still correct that I'm using 'smartlock' in the yaml right?

Https://pastebin.com/wr6BHPgB

**Comment by dauden1184** [comment]
> It's still correct that I'm using 'smartlock' in the yaml right?

yes, don't worry about that.


Looking at your logs it seems the software now correctly identify the device as the opener, and it's using the correct configuration mapping values (the one without the homekit status) but still it seems there is something different. can you try to run it with the verbose flag?

**Comment by maddingamer** [comment]
Okay, sry I didn't know there is a verbose flag for the script itself too (as it is already paired). But I ran with verbose now: https://pastebin.com/QY1DuagY

**Comment by dauden1184** [comment]
good, i probably fond the problem, try again please

**Comment by maddingamer** [comment]
Looks good to me, it's getting the name, location etc from the opener and stays at the last line without error or exiting. 

Https://pastebin.com/SHzMmb6h

What would be the next step?

**Comment by dauden1184** [comment]
perfect! next step would be to try some actions on the opener.
Are you planning to integrate this bridge with homeassistant, openhub or something like that?

**Comment by maddingamer** [comment]
I want to add it to homeassistant, yes :)

**Comment by dauden1184** [comment]
well you can already do it, just configure the official integration using the ip address of your raspberry and the token that is saved in your nuki.yaml file. let's see if it works!

**Comment by maddingamer** [comment]
Works, but without any entities or devices.

**Comment by dauden1184** [comment]
any errors in the software logs?

**Comment by maddingamer** [comment]
In ha logs it only says unknown device type: 1. Using the official integration.

**Comment by dauden1184** [comment]
ye, my DeviceType mapping was incorrect :(
Try to update the software and retry please

**Comment by maddingamer** [comment]
It seems to be still the same.
I'll try again tomorrow tho, unless you find something.

**Comment by dauden1184** [comment]
shoud be fixed now

**Comment by maddingamer** [comment]
> shoud be fixed now

Now it just says canceled when setting up the integration. Logs are empty.

**Comment by dauden1184** [comment]
The last edit was really a minor one, it shouldn't cause issues like this.
Try to remove the integration, restart the software and homeassistant and try it again.

**Comment by maddingamer** [comment]
I restarted HA again, reenabled the previously deactivated integration and it now shows one entity. But it says locked, even tho it's an opener and not a lock.

**Comment by dauden1184** [comment]
Looking at the homeassistant code and at the [documentation of the integration](https://www.home-assistant.io/integrations/nuki/#service-nukiset_continuous_mode), it seems that the integration is not totally ready for the opener, and right now the Ring-to-Open feature is mapped to the “lock/unlock” state. But it should work also with the wrong states name.

**Comment by maddingamer** [comment]
I tried the integration from hacs, which kind of seems to support the opener. At least it's finding both the opener and the bridge (Battery says 0% tho and it says locked here as well) 

I'll try the "unlock" button and sensors once I am home again on weekend and let you know if it works.

**Comment by maddingamer** [comment]
I tried the unlock and lock functions, no reactions 🤔

**Comment by dauden1184** [comment]
> (Battery says 0% tho and it says locked here as well)

Yeah, as opposed to the smartlock, the opener seems to not report the battery percentage, only if it is in critical state.

> I tried the unlock and lock functions, no reactions

Anything in the logs?

**Comment by maddingamer** [comment]
Yes indeed, it's only showing critical battery. Lock/unlock works now and it activates and disables the ring to open function (as described in the docs for hass_nuki_ng). But I have no entity for opening (service lock.open). I only got one entity (lock.nuki_mylock.lock), where i have two buttons, lock and unlock. But a state like lock.nuki_mylock.open is missing. So I am not able to activate the buzzer on the door.

**Comment by dauden1184** [comment]
> I tried the integration from hacs

Do you mean [this one?](https://github.com/kvj/hass_nuki_ng)

It seems that homeassistant dosen't have a button to launch the open command but in the integration linked above, [there is this](https://github.com/kvj/hass_nuki_ng#openunlatch-nuki-lock-via-ui).

So you should be able to add a button that launch the lock.open service

**Comment by maddingamer** [comment]
> > I tried the integration from hacs
> 
> Do you mean [this one?](https://github.com/kvj/hass_nuki_ng)
> 
> It seems that homeassistant dosen't have a button to launch the open command but in the integration linked above, [there is this](https://github.com/kvj/hass_nuki_ng#openunlatch-nuki-lock-via-ui).
> 
> So you should be able to add a button that launch the lock.open service

Yes you're right, I should read the Readme of that integration/repo next time 😅

Now I just need to figure out why the state is not changing when somebody is ringing on the door.

**Comment by maddingamer** [comment]
It seems my intercom is not registrating when somebody is ringing. Ring to open does not work and the state "ring action" is not changing at all. I think it might be a problem with my intercom. I'll look into it once I'm home.

**Comment by maddingamer** [comment]
Update: The ring action not beeing registered by homeassistant is related to your script/software bridge. I got a lock today with a hardware bridge and with that I get all items populated within HA. 
When using the software-bridge the entity of "ring action" says "not available" (using hass_nuki_ng). Switching to hardware bridge and it works. 

Let me know if you need further assistance to add support for the opener within your project, even tho I don't need it for myself anymore :)

**Comment by dauden1184** [comment]
Do you have any logs of the bridge in the moment when it should receive the ring action?

**Comment by aje89** [comment]
Maybe its possible to implement it leveraging the trigger value.
<html>
<body>


Name | Requirement | Format | Additional Information
-- | -- | -- | --
Trigger | M | uint8 | The trigger, that caused the state changewithin the Nuki Opener0x00 systemvia bluetooth command0x01 **manualby pressing the doorbell** button0x02 buttonby pressing the Nuki Opener button0x03 automaticExecuted automatically (e.g. at a specific time) by the Nuki Opener


</body>
</html>

**Comment by dauden1184** [comment]
The nuki devices send regularly an ibeacon with a value that notify that the device state is changed.
If the software bridge detect this value, it connect to the device and request the current state.

So the problem can be that the software don't detect the change of status.
Or it isn't checking the correct fields of the state, once requested.

I will need some logs of the software during a change of state of the opener in order to understand what is going on

**Comment by aje89** [comment]
i started the bridge with verbose flag. _python3 . --verbose_ 

Than i performed a ring:

Output is here:
https://pastebin.com/kHYc3Cw7

**Comment by dauden1184** [comment]
Thanks for the logs, I'm looking into it.
The initial state and the state received after the state change (so, i assume after your ring) seems to be the same =/
The trigger value is 0, so it's bluetooth command, but you ringed, right?

Anyway, the communication with the opener seems to works fine, it's probably just a problem with the http side of the software.

**Comment by dauden1184** [comment]
I think I got it. New release in the next days

**Comment by dauden1184** [comment]
@aje89  Give it a try please

@maddingamer can you describe a bit more what happen using the official bridge? what states are shown in homeassistant?thanks

**Comment by maddingamer** [comment]
> @maddingamer can you describe a bit more what happen using the official bridge? what states are shown in homeassistant?thanks

Sure. There are the following states for the opener (using nuki_ng and official hardware-bridge):

- binary_sensor.nuki_battery_critical
- binary_sensor.nuki_opener_locked (shows if door is locked, for opener it's if rto is active)
- binary_sensor.nuki_opener_ring_action (default off, switches to on when sb rang at the door, stays on for aprox. 30sec)
- lock.nuki_opener_lock (unlocking the lock triggers ring to open (rto), locking disables rto again)
- sensor.nuki_opener_firmware_version
- sensor.nuki_opener_rssi
- sensor.nuki_opener_state (shows "online" or "rto active")

As I remember primarly the ring_aciton was missing when using your software-bridge.
"Opener" in the states is changed with the name of the opener itself.

**Comment by aje89** [comment]
Just had a quick look into the new version. It seems that RingAction is always "ON" now.

I can gather logs later that day

**Comment by dauden1184** [comment]
Try to update again the software before checking the logs please

**Comment by aje89** [comment]
> 

https://pastebin.com/t9zrHbeN

**Comment by dauden1184** [comment]
Please update the software and try again

**Comment by technyon** [comment]
@dauden1184 Hi, could you elaborate on how to detect a ring action? It's not in the official docs, and I don't get an answer in the Nuki Developer Forum ...

**Comment by technyon** [comment]
I figured it out in the meantime. You'll find the answer here:

https://developer.nuki.io/t/nuki-opener-how-to-detect-ring-action/16392/7

Quoting myself:
--
If someone rings the doorbell, the opener signals a change in the “opener state” via iBeacon RSSI value change. The state doesn’t change though, which is how to detect a ring: Whenever the state “changes” from locked (0x01) to locked, one can assume that a ring was detected.
--
