### ISSUE TITLE
Works like a charm but

### ISSUE THREAD

**Issue by chr-braun** [dauden1184/RaspiNukiBridge#6]
please change in /etc/systemd/system/nukibridge.service

_WorkingDirectory=/home/pi/NukiBridge/_

to **WorkingDirectory=/home/pi/RaspiNukiBridge/**

thank you for your work.

**Comment by dauden1184** [comment]
Yes, I specified in the README to change the WorkingDirectory to your needs but I should put the correct default directory.

Done, thanks!

**Comment by chr-braun** [comment]
Thank you, i think, most people use copy and paste.
